core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('films.urls')),
]

films/urls.py
from django.urls import path


from . import views


app_name = "films"

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("film/<int:pk>/", views.film_detail, name="film_detail"),
]

films/models.py
from django.db import models


from django.db import models
from django.conf import settings  # Add this line to the the bottom of the imports

certs = [
    ("U", "U"),
    ("PG", "PG"),
    ("12a", "12a"),
    ("15", "15"),
    ("18", "18"),
]


class Film(models.Model):
    title = models.CharField(max_length=250)
    released = models.DateField(auto_now=False, auto_now_add=False)
    certificate = models.CharField(max_length=3, choices=certs)
    duration = models.DurationField()
    genre = models.CharField(max_length=100)
    director = models.CharField(max_length=250)
    star1 = models.CharField(max_length=250)
    star2 = models.CharField(max_length=250)
    star3 = models.CharField(max_length=250)
    star4 = models.CharField(max_length=250)
    overview = models.TextField(max_length=1000)
    poster = models.URLField(max_length=200)

    def __str__(self):
        return self.title


class Rating(models.Model):
    film = models.ForeignKey(Film, on_delete=models.CASCADE, related_name="ratings")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    rating = models.IntegerField()

    def __str__(self):
        return f"{self.film} - {self.user}"

films/views.py
from django.shortcuts import get_object_or_404, render

from .models import Film, Rating

def homepage(request):

    films = Film.objects.all()

    context = {"films":films}

    return render(request, "films/homepage.html", context)

def film_detail(request, pk):
    film = get_object_or_404(Film, pk=pk)

    context = {"film":film}

    return render(request, "films/film_detail.html", context)

films/templates/films/film_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IMDB</title>
</head>
<body>
        <h1>{{film.title}}</h1>
        <p>{{film.overview}}</p>
    
</body>
</html>

films/templates/films/homepage.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IMDB</title>
</head>

<body>
    <h1>IMDB clone</h1>
    <hr>
    {% for film in films %}
        <a href="{% url 'films:film_detail' film.pk %}">{{film.title}}</a>
    {% endfor %}

</body>

</html>